### PR TITLE
Relying on 7 characters can get us into an ambiguous situation

### PR DESCRIPTION
**Pull request by tlunter**
@nahiluhmot @adamjt @bfulton /cc @barnabyc

### CODE REVIEW

**Comment by adamjt** [comment]
LGTM - will this affect how relbot displays the SHA in Slack? (i.e. will we still show the short SHA in the [repo:env:sha] brackets for legibility?)

**Comment by bfulton** [comment]
What are the chances?!

(1/268435456) :game_die:

**Comment by nahiluhmot** [comment]
:+1:

**Comment by barnabyc** [comment]
I feel proud to have necessitated this!

**Pull request merged**
