### PR TITLE
Only import the base image when it is needed.

### PR DESCRIPTION
**Pull request by nahiluhmot**
@tlunter @bfulton @adamjt 

This is accomplished by giving each import a unique tag, and checking
for the tag before importing.

### CODE REVIEW

**Comment by tlunter** [comment]
:+1:

**Comment by adamjt** [comment]
Huh, I thought it was already smart about that. +1

**Comment by nahiluhmot** [comment]
@adamjt It was already smart about not re-downloading, but this fixes the re-importing. On some of our deploys, that can mean up to 90 seconds.

**Comment by adamjt** [comment]
Ah, cool. Every little bit counts!

**Comment by nahiluhmot** [comment]
Actually, more like 300 seconds.

**Pull request merged**
