### PR TITLE
Convert s3cmd to awscli.

### PR DESCRIPTION
**Pull request by adamjt**
@nahiluhmot @tlunter This uses the official AWS command line tools to interact with S3.

### CODE REVIEW

**Comment by adamjt** [comment]
@bfulton @tlunter circling back on this pull.

**Comment by tlunter** [comment]
Have you followed up on the region flag?

**Comment by adamjt** [comment]
Yes, that's the last commit.

**Comment by tlunter** [comment]
Can we document what version of aws cli we need? We'll need to rebase and change all the s3cmd to aws-cli. Unfortunately not two files anymore.

**Comment by adamjt** [comment]
I don't know specifically which version fixed it, but the version in the Ubuntu repos that doesn't work is 1.2.9-2, and the version I'm installing is 1.6.10. The most recent bug fix related to s3 regions was in version 1.6.3, so it's probably safe to say we require that as a bare minimum. https://aws.amazon.com/releasenotes/CLI/1089799671891305

**Comment by adamjt** [comment]
Instead of rebasing can we just do find/replace against a new branch? Might save some time.

**Comment by tlunter** [comment]
Just opened: https://github.com/swipely/dockly/pull/55

**Pull request closed without merging**
